### ISSUE TITLE
Problem parsing after float

### ISSUE THREAD

**Issue by berquist** [iwahbe/jsonian#37]
With the following example, after typing `true,` and hitting enter, the point is at the `*` rather than indented properly:
```json
{
    "float": 3.141,
    "bool": true,
*
}
```
and hitting tab gives:
```
jsonian--unexpected-char: jsonian-enclosing-item: unexpected character ’.’ at 2:14: expecting the end of a JSON value
    "float": 3.141,
              ^
```
It doesn't seem to matter if the value for the second entry is a boolean or another type.

**Comment by iwahbe** [comment]
Hey @berquist, thanks for pointing that out. I'm able to repro the problem and will have a fix coming shortly.
