### ISSUE TITLE
jsonian-find-path does display the value when ivy module is active in doom emacs

### ISSUE THREAD

**Issue by qiansheng91** [iwahbe/jsonian#42]
Here is my init.el
```
:Completion
  (ivy +fuzzy +icons)
```

here is the screen screenshot
![image](https://user-images.githubusercontent.com/81615037/231807542-6921f031-c167-4e1b-8739-02197b9b775c.png)

![image](https://user-images.githubusercontent.com/81615037/231809377-55f71733-1316-46ab-8563-9fb6cf6063a0.png)

**Comment by qiansheng91** [comment]
Thanks for your response. I want to display the value of keys like this:
![image](https://user-images.githubusercontent.com/81615037/231807542-6921f031-c167-4e1b-8739-02197b9b775c.png)

and when I active ivy module , the result looks like this:
 ![image](https://user-images.githubusercontent.com/81615037/231809377-55f71733-1316-46ab-8563-9fb6cf6063a0.png)

**Comment by iwahbe** [comment]
Thanks for clarifying. I use an Emacs feature called `affixation-function` to provide these annotations. It looks like Ivy doesn't support this feature: https://github.com/abo-abo/swiper/issues/2732. I'm not sure how Ivy wants me to do affixations, but a PR would be welcome.

In the meantime, I recommend upvoting https://github.com/abo-abo/swiper/issues/2732.

**Comment by qiansheng91** [comment]
Ok，Thanks.
