### ISSUE TITLE
Add to MELPA?

### ISSUE THREAD

**Issue by mkleehammer** [iwahbe/jsonian#8]
Great stuff, thanks.  Any chance you could get this onto MELPA?

**Comment by iwahbe** [comment]
I've started looking into the requirements for getting into MEPLA. This is definitely something I am interested in doing.

**Comment by iwahbe** [comment]
I have opened a [PR](https://github.com/melpa/melpa/pull/8074) to add `Jsonian` to MELPA.

**Comment by mkleehammer** [comment]
Great!  Thanks.

**Comment by iwahbe** [comment]
`jsonian` is in MELPA!
